(()=>{"use strict";
const SUPABASE_URL="https://apzsohskvnearnrcbqlq.supabase.co";
const SUPABASE_KEY="sb_publishable_NZ_JH0Bmh3kcTBayDLPFzQ_wDr9ZUca";
const overlay=document.getElementById("authOverlay"),trigger=document.getElementById("accountButton"),closeBtn=document.getElementById("authClose"),guestBtn=document.getElementById("authGuest"),tabs=[...document.querySelectorAll(".auth-tab")],loginForm=document.getElementById("loginForm"),signupForm=document.getElementById("signupForm"),accountView=document.getElementById("accountView"),heading=document.getElementById("authHeading"),intro=document.getElementById("authIntro"),message=document.getElementById("authMessage"),emailLabel=document.getElementById("authUserEmail"),signOutBtn=document.getElementById("signOutButton"),forgotBtn=document.getElementById("forgotPassword");
let client=null,currentUser=null;
function setMessage(text,type=""){message.textContent=text||"";message.className="auth-message"+(type?" "+type:"")}
function openAuth(mode=currentUser?"account":"login"){overlay.hidden=false;document.body.classList.add("auth-open");currentUser?showAccount():showMode(mode);setTimeout(()=>overlay.querySelector("input:not([type=hidden])")?.focus(),80)}
function closeAuth(){overlay.hidden=true;document.body.classList.remove("auth-open");setMessage("")}
function showMode(mode){const signup=mode==="signup";tabs.forEach(tab=>{const active=tab.dataset.authTab===mode;tab.classList.toggle("active",active);tab.setAttribute("aria-selected",String(active))});loginForm.hidden=signup;signupForm.hidden=!signup;accountView.hidden=true;document.getElementById("authTabs").hidden=false;heading.textContent=signup?"Create your account":"Welcome back";intro.textContent=signup?"Build your personal Gridiron Edge profile.":"Log in to continue with your Gridiron Edge account.";setMessage("")}
function showAccount(){document.getElementById("authTabs").hidden=true;loginForm.hidden=true;signupForm.hidden=true;accountView.hidden=false;heading.textContent="Your account";intro.textContent="You’re signed in to Gridiron Edge.";emailLabel.textContent=currentUser?.email||"Signed in";setMessage("")}
function syncUser(user){currentUser=user||null;if(currentUser){const name=currentUser.user_metadata?.display_name||currentUser.email?.split("@")[0]||"Account";trigger.textContent=name;trigger.classList.add("signed-in");trigger.setAttribute("aria-label","Open account for "+name)}else{trigger.textContent="Sign up / Log in";trigger.classList.remove("signed-in");trigger.setAttribute("aria-label","Sign up or log in")}}
function busy(form,on){form.querySelectorAll("button,input").forEach(el=>el.disabled=on)}
async function init(){if(!window.supabase){trigger.addEventListener("click",()=>openAuth());setMessage("Account service could not load. Please refresh and try again.","error");openAuth();return}client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await client.auth.getSession();syncUser(data.session?.user);client.auth.onAuthStateChange((_event,session)=>syncUser(session?.user));if(!currentUser)openAuth("signup")}
tabs.forEach(tab=>tab.addEventListener("click",()=>showMode(tab.dataset.authTab)));trigger.addEventListener("click",()=>openAuth());closeBtn.addEventListener("click",closeAuth);guestBtn.addEventListener("click",closeAuth);overlay.addEventListener("click",event=>{if(event.target===overlay)closeAuth()});document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!overlay.hidden)closeAuth()});
signupForm.addEventListener("submit",async event=>{event.preventDefault();setMessage("");const data=new FormData(signupForm),name=String(data.get("name")||"").trim(),email=String(data.get("email")||"").trim(),password=String(data.get("password")||"");if(password.length<8){setMessage("Use at least 8 characters for your password.","error");return}busy(signupForm,true);const {data:result,error}=await client.auth.signUp({email,password,options:{data:{display_name:name},emailRedirectTo:location.origin+location.pathname}});busy(signupForm,false);if(error){setMessage(error.message,"error");return}if(result.session){syncUser(result.user);showAccount()}else{setMessage("Account created. Check your email to confirm it, then log in.","success");signupForm.reset()}});
loginForm.addEventListener("submit",async event=>{event.preventDefault();setMessage("");const data=new FormData(loginForm);busy(loginForm,true);const {data:result,error}=await client.auth.signInWithPassword({email:String(data.get("email")||"").trim(),password:String(data.get("password")||"")});busy(loginForm,false);if(error){setMessage(error.message==="Invalid login credentials"?"That email or password is incorrect.":error.message,"error");return}syncUser(result.user);showAccount()});
forgotBtn.addEventListener("click",async()=>{const email=loginForm.elements.email.value.trim();if(!email){setMessage("Enter your email first, then choose Forgot password.","error");loginForm.elements.email.focus();return}forgotBtn.disabled=true;const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});forgotBtn.disabled=false;setMessage(error?error.message:"Password reset email sent.",error?"error":"success")});
signOutBtn.addEventListener("click",async()=>{signOutBtn.disabled=true;await client.auth.signOut();signOutBtn.disabled=false;syncUser(null);showMode("login");setMessage("You’ve been logged out.","success")});
init().catch(()=>{syncUser(null);openAuth("login");setMessage("Account service could not connect. Please refresh and try again.","error")});
})();