// Controlled paid-plan verification refresh
import { mkdir, readFile, writeFile } from "node:fs/promises";

const apiKey=process.env.ODDS_API_KEY?.trim();
const now=new Date();
const PROP_MARKETS=[
  "player_pass_yds","player_pass_tds","player_pass_completions","player_pass_attempts","player_pass_interceptions",
  "player_rush_yds","player_rush_attempts","player_reception_yds","player_receptions",
  "player_rush_reception_yds","player_anytime_td","player_kicking_points"
];
const PROP_BOOKMAKERS=["fanduel","draftkings","betmgm","caesars","hardrockbet","betrivers","espnbet","prizepicks","underdog"];
const quota={remaining:null,used:null,last:null};
const MARKET_LABELS={player_pass_yds:"Passing yards",player_pass_tds:"Passing TDs",player_pass_completions:"Pass completions",player_pass_attempts:"Pass attempts",player_pass_interceptions:"Interceptions thrown",player_pass_longest_completion:"Longest completion",player_rush_yds:"Rushing yards",player_rush_attempts:"Rush attempts",player_rush_longest:"Longest rush",player_reception_yds:"Receiving yards",player_receptions:"Receptions",player_reception_longest:"Longest reception",player_rush_reception_yds:"Rush + receiving yards",player_rush_tds:"Rushing TDs",player_reception_tds:"Receiving TDs",player_anytime_td:"Anytime TD",player_kicking_points:"Kicking points",player_field_goals:"Field goals made",player_fantasy_points:"Fantasy points"};
const CATEGORY={player_pass_yds:"Passing",player_pass_tds:"Passing",player_pass_completions:"Passing",player_pass_attempts:"Passing",player_pass_interceptions:"Passing",player_pass_longest_completion:"Passing",player_rush_yds:"Rushing",player_rush_attempts:"Rushing",player_rush_longest:"Rushing",player_reception_yds:"Receiving",player_receptions:"Receiving",player_reception_longest:"Receiving",player_rush_reception_yds:"Receiving",player_rush_tds:"Touchdowns",player_reception_tds:"Touchdowns",player_anytime_td:"Touchdowns",player_kicking_points:"Kicking",player_field_goals:"Kicking",player_fantasy_points:"Top Props"};
const BINARY_MARKETS=new Set(["player_anytime_td"]);
const providerLabel=book=>book?.title||book?.key||"Sportsbook";
const implied=price=>{const p=Number(price);if(!Number.isFinite(p)||p===0)return null;return p<0?(-p)/((-p)+100):100/(p+100)};
const round=(n,d=1)=>Number(Number(n).toFixed(d));
const clean=s=>String(s||"").trim();
function fairPairProbability(overPrice,underPrice){const o=implied(overPrice),u=implied(underPrice);if(o==null||u==null||o+u===0)return null;return {Over:o/(o+u),Under:u/(o+u)}}
function confidence(prob){if(prob>=0.60)return "High";if(prob>=0.55)return "Medium";return "Low"}
function summarizeEvent(event){return `${event.away_team} @ ${event.home_team}`}

const sk=v=>String(v||"").toLowerCase().normalize("NFD").replace(/[\\u0300-\\u036f]/g,"").replace(/[^a-z0-9]/g,"");
const sn=v=>{const m=String(v??"").replace(/,/g,"").match(/-?\\d+(?:\\.\\d+)?/);return m?Number(m[0]):null};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const erf=x=>{const s=x<0?-1:1,a=Math.abs(x),t=1/(1+.3275911*a);return s*(1-(((((1.061405429*t-1.453152027)*t+1.421413741)*t-.284496736)*t+.254829592)*t)*Math.exp(-a*a))};
const cdf=z=>.5*(1+erf(z/Math.SQRT2));
const floors={player_pass_yds:38,player_pass_tds:.65,player_pass_completions:3.5,player_pass_attempts:4.5,player_pass_interceptions:.55,player_rush_yds:15,player_rush_attempts:3,player_reception_yds:14,player_receptions:1.35,player_rush_reception_yds:18,player_kicking_points:2.4};
function boxPlayers(summary){const out=[];for(const tb of summary?.boxscore?.players||[]){const team=tb.team?.displayName||tb.team?.shortDisplayName||"",map=new Map(),get=name=>{const k=sk(name);if(!map.has(k))map.set(k,{name,team,pass:{},rush:{},rec:{},kick:{}});return map.get(k)};for(const group of tb.statistics||[]){const gn=String(group.name||group.type||"").toLowerCase(),labels=group.labels||group.names||[];for(const entry of group.athletes||[]){const name=entry.athlete?.displayName||entry.athlete?.fullName;if(!name)continue;const p=get(name),stats=entry.stats||entry.statistics||[];labels.forEach((label,i)=>{const tag=String(label).toUpperCase(),raw=stats[i];if(gn.includes("pass")){if(tag.includes("C/ATT")){const z=String(raw).split("/").map(sn);p.pass.comp=z[0];p.pass.att=z[1]}else if(tag==="YDS")p.pass.yds=sn(raw);else if(tag==="TD")p.pass.td=sn(raw);else if(tag==="INT")p.pass.int=sn(raw)}else if(gn.includes("rush")){if(tag==="CAR"||tag==="ATT")p.rush.att=sn(raw);else if(tag==="YDS")p.rush.yds=sn(raw);else if(tag==="TD")p.rush.td=sn(raw)}else if(gn.includes("receiv")){if(tag==="REC")p.rec.rec=sn(raw);else if(tag==="YDS")p.rec.yds=sn(raw);else if(tag==="TD")p.rec.td=sn(raw)}else if(gn.includes("kick")){if(tag==="FG")p.kick.fg=sn(String(raw).split("/")[0]);else if(tag==="XP")p.kick.xp=sn(String(raw).split("/")[0]);else if(tag==="PTS")p.kick.pts=sn(raw)}})}}out.push(...map.values())}return out}
function stat(m,p){const v={player_pass_yds:p.pass.yds,player_pass_tds:p.pass.td,player_pass_completions:p.pass.comp,player_pass_attempts:p.pass.att,player_pass_interceptions:p.pass.int,player_rush_yds:p.rush.yds,player_rush_attempts:p.rush.att,player_reception_yds:p.rec.yds,player_receptions:p.rec.rec,player_rush_reception_yds:Number.isFinite(p.rush.yds)&&Number.isFinite(p.rec.yds)?p.rush.yds+p.rec.yds:null,player_anytime_td:Number.isFinite(p.rush.td)||Number.isFinite(p.rec.td)?(p.rush.td||0)+(p.rec.td||0):null,player_kicking_points:Number.isFinite(p.kick.pts)?p.kick.pts:(Number.isFinite(p.kick.fg)||Number.isFinite(p.kick.xp)?(p.kick.fg||0)*3+(p.kick.xp||0):null)}[m];return Number.isFinite(v)?v:null}
async function hybridize(rows,schedule,league){
 const done=(schedule?.games||[]).filter(g=>(g.statusCompleted||/final/i.test(g.status||""))&&g.id).sort((a,b)=>new Date(b.date)-new Date(a.date)),need=new Set(rows.flatMap(r=>[sk(r.home),sk(r.away)])),games=new Map();
 for(const t of need){let n=0;for(const g of done)if(sk(g.home)===t||sk(g.away)===t){games.set(String(g.id),g);if(++n>=8)break}}
 const list=[...games.values()],summaries=new Map();let cursor=0;async function worker(){while(cursor<list.length){const g=list[cursor++],sport=league==="NFL"?"nfl":"college-football";try{summaries.set(String(g.id),await fetchJson("https://site.api.espn.com/apis/site/v2/sports/football/"+sport+"/summary?event="+g.id))}catch{}}}await Promise.all(Array.from({length:Math.min(10,list.length)},()=>worker()));
 const hist=new Map(),teams=new Map();for(const g of list)for(const p of boxPlayers(summaries.get(String(g.id)))){const pk=sk(p.name);if(!teams.has(pk))teams.set(pk,new Set());teams.get(pk).add(sk(p.team));for(const m of PROP_MARKETS){const v=stat(m,p);if(v==null)continue;const k=pk+"|"+m;if(!hist.has(k))hist.set(k,[]);hist.get(k).push({date:new Date(g.date).getTime(),v,team:sk(p.team)})}}
 const gameMap=new Map((schedule?.games||[]).map(g=>[sk(g.away)+"|"+sk(g.home),g])),out=[];
 for(const r of rows){const market=Number(r.hitProbability),eventTeams=new Set([sk(r.home),sk(r.away)]),known=teams.get(sk(r.player))||new Set();if(known.size&&![...known].some(t=>eventTeams.has(t))){out.push({...r,marketProbability:market,projectionType:"invalid-team",projectionSource:"Player does not match this event"});continue}const s=(hist.get(sk(r.player)+"|"+r.market)||[]).sort((a,b)=>b.date-a.date).slice(0,8);if(s.length<3){out.push({...r,marketProbability:market,projectionType:"insufficient-data",modelSample:s.length,projectionSource:"Not enough independent game logs"});continue}
 const w=s.map((_,i)=>Math.pow(.82,i)),ws=w.reduce((a,b)=>a+b,0),mean=s.reduce((a,x,i)=>a+x.v*w[i],0)/ws,variance=s.reduce((a,x,i)=>a+Math.pow(x.v-mean,2)*w[i],0)/ws,g=gameMap.get(sk(r.away)+"|"+sk(r.home)),home=sk(r.home)===s[0]?.team,score=Number(home?g?.prediction?.homeScore:g?.prediction?.awayScore),base=league==="NFL"?22.5:28,env=Number.isFinite(score)?clamp(score/base,.78,1.22):1,volume=/attempts|completions|receptions/.test(r.market),projection=mean*(1+(env-1)*(volume ? .45 : .75));let statistical;
 if(r.market==="player_anytime_td"){const hits=s.filter(x=>x.v>0).length,yes=clamp(((hits+1)/(s.length+2))*Math.sqrt(env),.08,.92);statistical=r.pick==="No"?1-yes:yes}else{const line=Number(r.line),sd=Math.max(Math.sqrt(variance),floors[r.market]||1);if(!Number.isFinite(line)){out.push({...r,marketProbability:market,projectionType:"insufficient-data"});continue}const over=1-cdf((line-projection)/sd);statistical=r.pick==="Under"?1-over:over}statistical=clamp(statistical,.05,.95);const blended=.5*statistical+.5*(market/100);out.push({...r,marketProbability:round(market),statisticalProbability:round(statistical*100),hitProbability:round(blended*100),confidence:confidence(blended),modelProjection:round(projection),modelSample:s.length,valueEdge:round(blended*100-market),projectionType:"hybrid",projectionSource:"50% independent ESPN game-log model + 50% no-vig market consensus",recentAverage:round(mean),recentStdDev:round(Math.sqrt(variance))})}return out}
async function fetchJson(url){const response=await fetch(url);const remaining=Number(response.headers.get("x-requests-remaining")),used=Number(response.headers.get("x-requests-used")),last=Number(response.headers.get("x-requests-last"));if(Number.isFinite(remaining))quota.remaining=remaining;if(Number.isFinite(used))quota.used=used;if(Number.isFinite(last))quota.last=last;const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(`${response.status}: ${body?.message||body?.error||"request failed"}`);return body}
async function fetchEvents(sport){const q=new URLSearchParams({apiKey,dateFormat:"iso"});const events=await fetchJson(`https://api.the-odds-api.com/v4/sports/${sport}/events?${q}`);const horizon=now.getTime()+8*86400000;return (Array.isArray(events)?events:[]).filter(e=>{const t=new Date(e.commence_time).getTime();return Number.isFinite(t)&&t>=now.getTime()-2*3600000&&t<=horizon}).sort((a,b)=>new Date(a.commence_time)-new Date(b.commence_time))}
async function fetchEventProps(sport,event){const q=new URLSearchParams({apiKey,bookmakers:PROP_BOOKMAKERS.join(","),markets:PROP_MARKETS.join(","),oddsFormat:"american",dateFormat:"iso",includeMultipliers:"true"});try{return await fetchJson(`https://api.the-odds-api.com/v4/sports/${sport}/events/${event.id}/odds?${q}`)}catch(error){console.error(`${sport} ${event.away_team} @ ${event.home_team}: ${error.message}`);return null}}
function propRow(event,book,market,player,line,pick,offer,prob){return {id:`${event.id}:${market.key}:${player}:${book.key}:${line}:${pick}`,eventId:event.id,commenceTime:event.commence_time,matchup:summarizeEvent(event),home:event.home_team,away:event.away_team,player,market:market.key,marketLabel:MARKET_LABELS[market.key]||market.key.replace(/^player_/,"").replaceAll("_"," "),category:CATEGORY[market.key]||"Top Props",providerKey:book.key,provider:providerLabel(book),line,pick,price:offer?.price??null,multiplier:offer?.multiplier??null,hitProbability:round(prob*100),confidence:confidence(prob),capturedAt:now.toISOString(),headshot:null}}
function normalizeEvent(event,data){if(!data?.bookmakers?.length)return [];const rows=[];for(const book of data.bookmakers){for(const market of book.markets||[]){if(BINARY_MARKETS.has(market.key)){for(const outcome of market.outcomes||[]){const namedSide=/^(yes|no)$/i.test(outcome.name||"")?outcome.name:null;const player=clean(outcome.description||outcome.player||(namedSide?"":outcome.name));if(!player)continue;const pick=namedSide?namedSide[0].toUpperCase()+namedSide.slice(1).toLowerCase():"Yes",prob=implied(outcome.price)||.5;rows.push(propRow(event,book,market,player,Number.isFinite(Number(outcome.point))?Number(outcome.point):0.5,pick,outcome,prob))}continue}const byKey=new Map();for(const outcome of market.outcomes||[]){const player=clean(outcome.description||outcome.player||outcome.name),side=outcome.name==="Over"||outcome.name==="Under"?outcome.name:null,line=Number(outcome.point);if(!player||!side||!Number.isFinite(line))continue;const key=`${player}|${line}`;if(!byKey.has(key))byKey.set(key,{player,line});byKey.get(key)[side]={price:outcome.price,multiplier:outcome.multiplier??null}}for(const pair of byKey.values()){if(!pair.Over&&!pair.Under)continue;const fair=pair.Over&&pair.Under?fairPairProbability(pair.Over.price,pair.Under.price):null;let pick="Over",prob=.5;if(fair){pick=fair.Over>=fair.Under?"Over":"Under";prob=Math.max(fair.Over,fair.Under)}else if(pair.Over){pick="Over";prob=implied(pair.Over.price)||.5}else{pick="Under";prob=implied(pair.Under.price)||.5}const chosen=pair[pick];rows.push(propRow(event,book,market,pair.player,pair.line,pick,chosen,prob))}}}return rows}
function dedupeAndRank(rows){const seen=new Set(),out=[];rows.sort((a,b)=>b.hitProbability-a.hitProbability||new Date(a.commenceTime)-new Date(b.commenceTime));for(const row of rows){const key=`${row.eventId}|${row.player}|${row.market}|${row.providerKey}|${row.line}`;if(seen.has(key))continue;seen.add(key);out.push(row)}return out}
function findEspnHeadshot(value){const queue=[value],seen=new Set();while(queue.length){const item=queue.shift();if(item==null)continue;if(typeof item==="string"){if(/^https?:\/\//i.test(item)&&/espncdn\.com/i.test(item)&&/(headshot|athletes)/i.test(item))return item;continue}if(typeof item!=="object"||seen.has(item))continue;seen.add(item);for(const v of Object.values(item))queue.push(v)}return null}
async function espnHeadshot(player,league){try{const q=new URLSearchParams({query:player,limit:"8"});const data=await fetchJson(`https://site.web.api.espn.com/apis/common/v3/search?${q}`);const sportWord=league==="NFL"?"nfl":"college",candidates=[];const walk=value=>{if(!value)return;if(Array.isArray(value)){for(const item of value)walk(item);return}if(typeof value!=="object")return;const text=JSON.stringify(value).toLowerCase();if(text.includes(player.split(" ").pop().toLowerCase())&&(text.includes(sportWord)||text.includes("football")))candidates.push(value);for(const v of Object.values(value))if(typeof v==="object")walk(v)};walk(data);for(const candidate of candidates){const url=findEspnHeadshot(candidate);if(url)return url}return findEspnHeadshot(data)}catch{return null}}
async function enrichHeadshots(rows,league){const names=[...new Set(rows.slice(0,180).map(r=>r.player))],result=new Map();let cursor=0;async function worker(){while(cursor<names.length){const name=names[cursor++];result.set(name,await espnHeadshot(name,league))}}await Promise.all(Array.from({length:Math.min(8,names.length)},()=>worker()));for(const row of rows)row.headshot=result.get(row.player)||row.headshot||null}
async function readPrevious(path){try{return JSON.parse(await readFile(path,"utf8"))}catch{return null}}
function usablePrevious(previous){const props=previous?.props||[];return props.length?{...previous,players:undefined,props,providers:[...new Set(props.map(p=>p.provider).filter(Boolean))].sort(),notice:"Using saved weekly prop lines while the provider refreshes."}:null}
async function build(sport,label,maxEvents,previous,schedule){
  if(!apiKey){const old=usablePrevious(previous);return old||{updatedAt:now.toISOString(),league:label,source:"The Odds API",props:[],notice:"ODDS_API_KEY is not configured"}}
  const events=(await fetchEvents(sport)).slice(0,maxEvents),props=[],checked=[];for(const event of events){if(quota.remaining!=null&&quota.remaining<PROP_MARKETS.length+200)break;const data=await fetchEventProps(sport,event);checked.push(event);if(data)props.push(...normalizeEvent(event,data))}
  const ranked=dedupeAndRank(props);
  if(!ranked.length){const old=usablePrevious(previous);if(old)return old}
  const archived=previous?.props||[],merged=dedupeAndRank([...ranked,...archived]);
  await enrichHeadshots(ranked,label);
  const projected=await hybridize(merged,schedule,label);
  return {updatedAt:now.toISOString(),league:label,source:"50% independent ESPN game-log projection + 50% no-vig sportsbook consensus",eventsChecked:checked.length,quota:{remaining:quota.remaining,used:quota.used,lastRequest:quota.last,estimatedCostPerEvent:PROP_MARKETS.length},providers:[...new Set(projected.map(p=>p.provider))].sort(),projectionModel:{version:1,type:"hybrid",statisticalWeight:.5,marketWeight:.5,minGames:3,recentGames:8},props:projected};
}
await mkdir("data",{recursive:true});
const [previousNfl,previousCfb,nflSchedule,cfbSchedule]=await Promise.all([readPrevious("data/props-nfl.json"),readPrevious("data/props-cfb.json"),readPrevious("data/nfl.json"),readPrevious("data/live.json")]);
const [nfl,cfb]=await Promise.all([build("americanfootball_nfl","NFL",24,previousNfl,nflSchedule),build("americanfootball_ncaaf","College Football",36,previousCfb,cfbSchedule)]);
await writeFile("data/props-nfl.json",JSON.stringify(nfl,null,2));await writeFile("data/props-cfb.json",JSON.stringify(cfb,null,2));console.log(`Player props: NFL ${nfl.props.length}, CFB ${cfb.props.length}`);
